### ISSUE TITLE
Getting an invoke on a null object exception 

### ISSUE THREAD

**Issue by jackpeters667** [Michocio/Puzzles-game#1]
s`  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
        at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:706)
        at com.example.micha.puzzle.Picture.decodeSampledBitmapFromPath(Picture.java:94)
        at com.example.micha.puzzle.Picture.getPicture(Picture.java:106)
        at com.example.micha.puzzle.Game.onCreate(Game.java:129)`

**Comment by jackpeters667** [comment]
The image taken by the camera does get added to the app though. But i'm trying to figure out how to stop that exception.  


-- Also on a runtime thing, the counter still goes on after I finish the puzzle. Is it not supposed to stop and take me to the GameFinished class
